title: "LIQCS 2026"
description: "Logic in Quantum Computer Science"
remote_theme: daattali/beautiful-jekyll

# navbar-links:
#   Programme: "programme"
#   Call for Contributions: "cfp"
#   Organisers: "organisers"

# MathJax 
mathjax: true

plugins:
  - jekyll-remote-theme
